name: Android Instrumentation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  instrumentation-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0

      - name: Set up JDK 11
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run tests
        run: ./gradlew connectedAndroidTest
